FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# COPY src/prisma ./src/prisma
RUN npm install

COPY . .

RUN npx prisma generate || true

# Install development tools
RUN npm install -g @nestjs/cli

EXPOSE 3002

CMD ["npm", "run", "start:dev"]

