/**
 * One-off seed: populate catalog_models for the 76 brands added by
 * seed-nhtsa-makes.ts, using NHTSA's vPIC API
 * (GetModelsForMakeYear/make/{make}/vehicletype/Passenger%20Car), which
 * excludes motorcycles/trucks/ATVs that a plain GetModelsForMake call would
 * include. Output was manually spot-checked and lightly cleaned (dropped a
 * handful of placeholder/cross-brand entries). Safe to re-run — upserts by
 * (makeId, slug), so already-seeded models are no-ops.
 *
 * Usage: pnpm ts-node scripts/seed-nhtsa-models.ts
 */
import { PrismaClient } from '../generated/client';

const prisma = new PrismaClient();

const MAKE_MODELS: Array<{ makeSlug: string; models: Array<{ name: string; slug: string }> }> = [
  {
    makeSlug: "acura",
    models: [
      { name: "RL", slug: "rl" },
      { name: "TL", slug: "tl" },
      { name: "TSX", slug: "tsx" },
      { name: "RLX", slug: "rlx" },
      { name: "ILX", slug: "ilx" },
      { name: "RSX", slug: "rsx" },
      { name: "Integra", slug: "integra" },
      { name: "CL", slug: "cl" },
      { name: "NSX", slug: "nsx" },
      { name: "Legend", slug: "legend" },
      { name: "TLX", slug: "tlx" },
      { name: "Vigor", slug: "vigor" },
    ],
  },
  {
    makeSlug: "alfa-romeo",
    models: [
      { name: "4C", slug: "4c" },
      { name: "8C Competizione Spider", slug: "8c-competizione-spider" },
      { name: "164", slug: "164" },
      { name: "Giulia (952)", slug: "giulia-952" },
      { name: "Spider", slug: "spider" },
      { name: "Milano", slug: "milano" },
      { name: "GTV6", slug: "gtv6" },
      { name: "Tonale", slug: "tonale" },
    ],
  },
  {
    makeSlug: "am-general",
    models: [
      { name: "MV-1", slug: "mv-1" },
    ],
  },
  {
    makeSlug: "american-motors",
    models: [
      { name: "Eagle 30", slug: "eagle-30" },
      { name: "Eagle 50", slug: "eagle-50" },
      { name: "Concord", slug: "concord" },
      { name: "Spirit", slug: "spirit" },
    ],
  },
  {
    makeSlug: "aston-martin",
    models: [
      { name: "V8 Vantage", slug: "v8-vantage" },
      { name: "DBS", slug: "dbs" },
      { name: "DB9", slug: "db9" },
      { name: "Rapide", slug: "rapide" },
      { name: "V12 Vantage", slug: "v12-vantage" },
      { name: "Virage", slug: "virage" },
      { name: "Vanquish", slug: "vanquish" },
      { name: "DB11", slug: "db11" },
      { name: "Lagonda", slug: "lagonda" },
      { name: "Vantage", slug: "vantage" },
      { name: "V8", slug: "v8" },
      { name: "Vanquish Zagato", slug: "vanquish-zagato" },
      { name: "DBX", slug: "dbx" },
      { name: "DB12", slug: "db12" },
      { name: "Valour", slug: "valour" },
      { name: "DB7", slug: "db7" },
      { name: "Valiant", slug: "valiant" },
      { name: "Valhalla", slug: "valhalla" },
    ],
  },
  {
    makeSlug: "pininfarina",
    models: [
      { name: "Battista", slug: "battista" },
      { name: "Azzurra", slug: "azzurra" },
    ],
  },
  {
    makeSlug: "bentley",
    models: [
      { name: "Brooklands", slug: "brooklands" },
      { name: "Azure", slug: "azure" },
      { name: "Turbo", slug: "turbo" },
      { name: "Mulsanne", slug: "mulsanne" },
      { name: "Flying Spur", slug: "flying-spur" },
      { name: "Eight", slug: "eight" },
      { name: "Arnage", slug: "arnage" },
      { name: "ARMOURED ARNAGE", slug: "armoured-arnage" },
      { name: "Continental", slug: "continental" },
    ],
  },
  {
    makeSlug: "bugatti",
    models: [
      { name: "Veyron", slug: "veyron" },
      { name: "Chiron", slug: "chiron" },
      { name: "EB110", slug: "eb110" },
      { name: "Chiron Pur Sport", slug: "chiron-pur-sport" },
      { name: "Chiron Supersport", slug: "chiron-supersport" },
      { name: "Mistral", slug: "mistral" },
    ],
  },
  {
    makeSlug: "buick",
    models: [
      { name: "LaCrosse", slug: "lacrosse" },
      { name: "Regal", slug: "regal" },
      { name: "Verano", slug: "verano" },
      { name: "Lucerne", slug: "lucerne" },
      { name: "Allure", slug: "allure" },
      { name: "Park Avenue", slug: "park-avenue" },
      { name: "LeSabre", slug: "lesabre" },
      { name: "Century", slug: "century" },
      { name: "Riviera", slug: "riviera" },
      { name: "Skylark", slug: "skylark" },
      { name: "Roadmaster", slug: "roadmaster" },
      { name: "Cascada", slug: "cascada" },
      { name: "Reatta", slug: "reatta" },
      { name: "Electra", slug: "electra" },
      { name: "Skyhawk", slug: "skyhawk" },
      { name: "Somerset", slug: "somerset" },
      { name: "Regal TourX", slug: "regal-tourx" },
    ],
  },
  {
    makeSlug: "byd",
    models: [
      { name: "e6", slug: "e6" },
    ],
  },
  {
    makeSlug: "cadillac",
    models: [
      { name: "ATS", slug: "ats" },
      { name: "CTS", slug: "cts" },
      { name: "ELR", slug: "elr" },
      { name: "XTS", slug: "xts" },
      { name: "STS", slug: "sts" },
      { name: "DTS", slug: "dts" },
      { name: "XLR", slug: "xlr" },
      { name: "Limousine", slug: "limousine" },
      { name: "Hearse", slug: "hearse" },
      { name: "Deville", slug: "deville" },
      { name: "Eldorado", slug: "eldorado" },
      { name: "Catera", slug: "catera" },
      { name: "Seville", slug: "seville" },
      { name: "Commercial Chassis", slug: "commercial-chassis" },
      { name: "Fleetwood", slug: "fleetwood" },
      { name: "CT6", slug: "ct6" },
      { name: "60 Special", slug: "60-special" },
      { name: "Allante", slug: "allante" },
      { name: "Brougham", slug: "brougham" },
      { name: "Cimarron", slug: "cimarron" },
      { name: "CT4", slug: "ct4" },
      { name: "CT5", slug: "ct5" },
      { name: "Celestiq", slug: "celestiq" },
    ],
  },
  {
    makeSlug: "checker",
    models: [
      { name: "A-11", slug: "a-11" },
      { name: "A-12", slug: "a-12" },
    ],
  },
  {
    makeSlug: "chevrolet",
    models: [
      { name: "Aveo", slug: "aveo" },
      { name: "Camaro", slug: "camaro" },
      { name: "Caprice Police Vehicle", slug: "caprice-police-vehicle" },
      { name: "Corvette", slug: "corvette" },
      { name: "Cruze", slug: "cruze" },
      { name: "Impala", slug: "impala" },
      { name: "Malibu", slug: "malibu" },
      { name: "Sonic", slug: "sonic" },
      { name: "Spark", slug: "spark" },
      { name: "SS", slug: "ss" },
      { name: "Volt", slug: "volt" },
      { name: "Geo Prizm", slug: "geo-prizm" },
      { name: "Matiz", slug: "matiz" },
      { name: "Cobalt", slug: "cobalt" },
      { name: "Optra", slug: "optra" },
      { name: "Kalos", slug: "kalos" },
      { name: "Monte Carlo", slug: "monte-carlo" },
      { name: "Epica", slug: "epica" },
      { name: "Cavalier", slug: "cavalier" },
      { name: "U100", slug: "u100" },
      { name: "Lumina", slug: "lumina" },
      { name: "Alero", slug: "alero" },
      { name: "Caprice", slug: "caprice" },
      { name: "Corsica", slug: "corsica" },
      { name: "Beretta", slug: "beretta" },
      { name: "Hearse/Limo", slug: "hearse-limo" },
      { name: "Metro", slug: "metro" },
      { name: "Impala Limited", slug: "impala-limited" },
      { name: "Bolt EV", slug: "bolt-ev" },
      { name: "Hearse/Limo Commercial Chassis", slug: "hearse-limo-commercial-chassis" },
      { name: "Celebrity", slug: "celebrity" },
      { name: "Geo Spectrum", slug: "geo-spectrum" },
      { name: "Chevette", slug: "chevette" },
      { name: "Geo Sprint", slug: "geo-sprint" },
      { name: "Nova", slug: "nova" },
      { name: "Citation", slug: "citation" },
      { name: "Malibu Classic", slug: "malibu-classic" },
      { name: "Onix", slug: "onix" },
      { name: "Bolt EUV", slug: "bolt-euv" },
      { name: "Cruze Limited", slug: "cruze-limited" },
      { name: "Malibu Limited", slug: "malibu-limited" },
      { name: "Bolt", slug: "bolt" },
    ],
  },
  {
    makeSlug: "chrysler",
    models: [
      { name: "Cirrus", slug: "cirrus" },
      { name: "Sebring", slug: "sebring" },
      { name: "300", slug: "300" },
      { name: "200", slug: "200" },
      { name: "PT Cruiser", slug: "pt-cruiser" },
      { name: "Crossfire", slug: "crossfire" },
      { name: "Concorde", slug: "concorde" },
      { name: "Intrepid", slug: "intrepid" },
      { name: "New Yorker", slug: "new-yorker" },
      { name: "LHS", slug: "lhs" },
      { name: "Vision", slug: "vision" },
      { name: "Stratus", slug: "stratus" },
      { name: "Viper", slug: "viper" },
      { name: "Neon", slug: "neon" },
      { name: "Shadow", slug: "shadow" },
      { name: "Prowler", slug: "prowler" },
      { name: "TC", slug: "tc" },
      { name: "LeBaron", slug: "lebaron" },
      { name: "Concorde/LHS", slug: "concorde-lhs" },
      { name: "Daytona", slug: "daytona" },
      { name: "Dynasty", slug: "dynasty" },
      { name: "Imperial", slug: "imperial" },
      { name: "SALON", slug: "salon" },
      { name: "Laser", slug: "laser" },
      { name: "NEWPORT", slug: "newport" },
      { name: "FIFTH AVENUE", slug: "fifth-avenue" },
      { name: "Conquest", slug: "conquest" },
      { name: "EXECUTIVE", slug: "executive" },
      { name: "E-CLASS", slug: "e-class" },
      { name: "Cordoba", slug: "cordoba" },
      { name: "300C", slug: "300c" },
    ],
  },
  {
    makeSlug: "daewoo",
    models: [
      { name: "LANOS", slug: "lanos" },
      { name: "NUBIRA", slug: "nubira" },
      { name: "LEGANZA", slug: "leganza" },
      { name: "Laganza V-car", slug: "laganza-v-car" },
      { name: "Leganza V-200 & variants/derivatives", slug: "leganza-v-200-and-variants-derivatives" },
      { name: "G2X", slug: "g2x" },
    ],
  },
  {
    makeSlug: "daihatsu",
    models: [
      { name: "Charade", slug: "charade" },
    ],
  },
  {
    makeSlug: "datsun",
    models: [
      { name: "210", slug: "210" },
      { name: "310", slug: "310" },
      { name: "510", slug: "510" },
      { name: "280ZX", slug: "280zx" },
    ],
  },
  {
    makeSlug: "delorean",
    models: [
      { name: "DMC-12", slug: "dmc-12" },
    ],
  },
  {
    makeSlug: "dodge",
    models: [
      { name: "Avenger", slug: "avenger" },
      { name: "Challenger", slug: "challenger" },
      { name: "Charger", slug: "charger" },
      { name: "Caliber", slug: "caliber" },
      { name: "Viper", slug: "viper" },
      { name: "Ram", slug: "ram" },
      { name: "Dart", slug: "dart" },
      { name: "Intrepid", slug: "intrepid" },
      { name: "Stratus", slug: "stratus" },
      { name: "Neon", slug: "neon" },
      { name: "Colt", slug: "colt" },
      { name: "Stealth", slug: "stealth" },
      { name: "Spirit", slug: "spirit" },
      { name: "Shadow", slug: "shadow" },
      { name: "Dynasty", slug: "dynasty" },
      { name: "Daytona", slug: "daytona" },
      { name: "Monaco", slug: "monaco" },
      { name: "OMNI", slug: "omni" },
      { name: "Shelby Charger", slug: "shelby-charger" },
      { name: "ARIES", slug: "aries" },
      { name: "600", slug: "600" },
      { name: "DIPLOMAT", slug: "diplomat" },
      { name: "LANCER", slug: "lancer" },
      { name: "Conquest", slug: "conquest" },
      { name: "400", slug: "400" },
      { name: "Mirada", slug: "mirada" },
      { name: "ST.REGIS", slug: "st-regis" },
    ],
  },
  {
    makeSlug: "dongfeng",
    models: [
      { name: "Sport", slug: "sport" },
      { name: "Rear drive motor", slug: "rear-drive-motor" },
      { name: "Front drive motor", slug: "front-drive-motor" },
    ],
  },
  {
    makeSlug: "eagle",
    models: [
      { name: "Summit", slug: "summit" },
      { name: "Talon", slug: "talon" },
      { name: "Vision", slug: "vision" },
      { name: "2000 GTX", slug: "2000-gtx" },
      { name: "PREMIER", slug: "premier" },
      { name: "VISTA", slug: "vista" },
      { name: "MEDALLION", slug: "medallion" },
    ],
  },
  {
    makeSlug: "ferrari",
    models: [
      { name: "612 Scaglietti", slug: "612-scaglietti" },
      { name: "599", slug: "599" },
      { name: "599 GTB Fiorano", slug: "599-gtb-fiorano" },
      { name: "430", slug: "430" },
      { name: "F430", slug: "f430" },
      { name: "360", slug: "360" },
      { name: "575M Maranello", slug: "575m-maranello" },
      { name: "456M", slug: "456m" },
      { name: "Enzo", slug: "enzo" },
      { name: "F355", slug: "f355" },
      { name: "550 Maranello", slug: "550-maranello" },
      { name: "F12 Berlinetta", slug: "f12-berlinetta" },
      { name: "California T", slug: "california-t" },
      { name: "FF", slug: "ff" },
      { name: "La Ferrari", slug: "la-ferrari" },
      { name: "458 Italia", slug: "458-italia" },
      { name: "458", slug: "458" },
      { name: "California", slug: "california" },
      { name: "348 tb", slug: "348-tb" },
      { name: "348 ts", slug: "348-ts" },
      { name: "512 TR", slug: "512-tr" },
      { name: "355 Berlinetta", slug: "355-berlinetta" },
      { name: "355 GTS", slug: "355-gts" },
      { name: "348 Spider", slug: "348-spider" },
      { name: "456", slug: "456" },
      { name: "355 Spider", slug: "355-spider" },
      { name: "Mondial T", slug: "mondial-t" },
      { name: "Testarossa", slug: "testarossa" },
      { name: "F40", slug: "f40" },
      { name: "328 GTB", slug: "328-gtb" },
      { name: "328 GTS", slug: "328-gts" },
      { name: "3.2 Mondial", slug: "3-2-mondial" },
      { name: "328", slug: "328" },
      { name: "308GTB Quattrovalvole", slug: "308gtb-quattrovalvole" },
      { name: "308GTS Quattrovalvole", slug: "308gts-quattrovalvole" },
      { name: "Mondial 8", slug: "mondial-8" },
      { name: "308 Convertible", slug: "308-convertible" },
      { name: "F12 Special Series", slug: "f12-special-series" },
      { name: "F60 America", slug: "f60-america" },
      { name: "308GTBi", slug: "308gtbi" },
      { name: "308GTSi", slug: "308gtsi" },
      { name: "308GTB", slug: "308gtb" },
      { name: "308GTS", slug: "308gts" },
      { name: "F12 tdf (Tour de France)", slug: "f12-tdf-tour-de-france" },
      { name: "GTC4Lusso", slug: "gtc4lusso" },
      { name: "488", slug: "488" },
      { name: "Portofino", slug: "portofino" },
      { name: "812", slug: "812" },
      { name: "F8", slug: "f8" },
      { name: "Roma", slug: "roma" },
      { name: "Challenge Stradale", slug: "challenge-stradale" },
      { name: "Portofino M", slug: "portofino-m" },
      { name: "SF90", slug: "sf90" },
      { name: "550 Barchetta", slug: "550-barchetta" },
      { name: "F50", slug: "f50" },
      { name: "Monza SP1/SP2", slug: "monza-sp1-sp2" },
      { name: "Daytona SP3", slug: "daytona-sp3" },
      { name: "296", slug: "296" },
      { name: "12Cilindri", slug: "12cilindri" },
      { name: "F80", slug: "f80" },
      { name: "849 Testarossa", slug: "849-testarossa" },
      { name: "296 Speciale", slug: "296-speciale" },
      { name: "296 Speciale A", slug: "296-speciale-a" },
      { name: "Luce", slug: "luce" },
      { name: "Amalfi", slug: "amalfi" },
    ],
  },
  {
    makeSlug: "fiat",
    models: [
      { name: "500", slug: "500" },
      { name: "124 Spider", slug: "124-spider" },
      { name: "Spider 2000", slug: "spider-2000" },
      { name: "X 1/9", slug: "x-1-9" },
      { name: "Brava", slug: "brava" },
      { name: "Strada", slug: "strada" },
      { name: "500e", slug: "500e" },
    ],
  },
  {
    makeSlug: "fisker",
    models: [
      { name: "Karma", slug: "karma" },
      { name: "Nina", slug: "nina" },
    ],
  },
  {
    makeSlug: "genesis",
    models: [
      { name: "G80", slug: "g80" },
      { name: "G90", slug: "g90" },
      { name: "G70", slug: "g70" },
    ],
  },
  {
    makeSlug: "geo",
    models: [
      { name: "Metro", slug: "metro" },
      { name: "Storm", slug: "storm" },
      { name: "Prizm", slug: "prizm" },
      { name: "Sprint", slug: "sprint" },
      { name: "Spectrum", slug: "spectrum" },
      { name: "505", slug: "505" },
      { name: "405", slug: "405" },
      { name: "604", slug: "604" },
      { name: "504", slug: "504" },
    ],
  },
  {
    makeSlug: "glickenhaus",
    models: [
      { name: "004", slug: "004" },
      { name: "007", slug: "007" },
      { name: "003S", slug: "003s" },
      { name: "003CS", slug: "003cs" },
      { name: "003C", slug: "003c" },
      { name: "004S", slug: "004s" },
      { name: "004CS", slug: "004cs" },
      { name: "004C", slug: "004c" },
      { name: "005S", slug: "005s" },
      { name: "005CS", slug: "005cs" },
      { name: "005C", slug: "005c" },
      { name: "006S", slug: "006s" },
      { name: "006CS", slug: "006cs" },
      { name: "006C", slug: "006c" },
      { name: "007CS", slug: "007cs" },
      { name: "008S", slug: "008s" },
      { name: "002S", slug: "002s" },
      { name: "002CS", slug: "002cs" },
    ],
  },
  {
    makeSlug: "gmc",
    models: [
      { name: "Electric Vehicle", slug: "electric-vehicle" },
    ],
  },
  {
    makeSlug: "holden",
    models: [
      { name: "Volt", slug: "volt" },
    ],
  },
  {
    makeSlug: "honda",
    models: [
      { name: "Accord", slug: "accord" },
      { name: "Civic", slug: "civic" },
      { name: "Odyssey", slug: "odyssey" },
      { name: "Insight", slug: "insight" },
      { name: "FCX Clarity", slug: "fcx-clarity" },
      { name: "Fit", slug: "fit" },
      { name: "CR-Z", slug: "cr-z" },
      { name: "S2000", slug: "s2000" },
      { name: "Prelude", slug: "prelude" },
      { name: "del Sol", slug: "del-sol" },
      { name: "EV Plus", slug: "ev-plus" },
      { name: "Clarity", slug: "clarity" },
      { name: "Civic Si", slug: "civic-si" },
      { name: "Civic Type R", slug: "civic-type-r" },
    ],
  },
  {
    makeSlug: "infiniti",
    models: [
      { name: "QX50", slug: "qx50" },
      { name: "Q40", slug: "q40" },
      { name: "Q50", slug: "q50" },
      { name: "Q60", slug: "q60" },
      { name: "Q70", slug: "q70" },
      { name: "Q70L", slug: "q70l" },
      { name: "Q45", slug: "q45" },
      { name: "G35", slug: "g35" },
      { name: "M35", slug: "m35" },
      { name: "M45", slug: "m45" },
      { name: "G37", slug: "g37" },
      { name: "EX35", slug: "ex35" },
      { name: "M56", slug: "m56" },
      { name: "M37", slug: "m37" },
      { name: "G25", slug: "g25" },
      { name: "M35h", slug: "m35h" },
      { name: "J30", slug: "j30" },
      { name: "G20", slug: "g20" },
      { name: "I35", slug: "i35" },
      { name: "I30", slug: "i30" },
      { name: "M30", slug: "m30" },
      { name: "QX30", slug: "qx30" },
    ],
  },
  {
    makeSlug: "isuzu",
    models: [
      { name: "IMPULSE", slug: "impulse" },
      { name: "I-Mark", slug: "i-mark" },
      { name: "Stylus", slug: "stylus" },
    ],
  },
  {
    makeSlug: "jaguar",
    models: [
      { name: "XJ", slug: "xj" },
      { name: "XF", slug: "xf" },
      { name: "XK", slug: "xk" },
      { name: "X-Type", slug: "x-type" },
      { name: "S-Type", slug: "s-type" },
      { name: "F-TYPE", slug: "f-type" },
      { name: "Vanden Plas", slug: "vanden-plas" },
      { name: "XK8", slug: "xk8" },
      { name: "XJR", slug: "xjr" },
      { name: "XE", slug: "xe" },
      { name: "XJ8", slug: "xj8" },
      { name: "XJ6", slug: "xj6" },
      { name: "XJS", slug: "xjs" },
      { name: "XJ12", slug: "xj12" },
    ],
  },
  {
    makeSlug: "karma",
    models: [
      { name: "Atlantic", slug: "atlantic" },
      { name: "Revero", slug: "revero" },
      { name: "Revero GT", slug: "revero-gt" },
      { name: "GS-6", slug: "gs-6" },
      { name: "Kaveya", slug: "kaveya" },
      { name: "Gyesera", slug: "gyesera" },
    ],
  },
  {
    makeSlug: "koenigsegg",
    models: [
      { name: "One:1", slug: "one-1" },
      { name: "Agera", slug: "agera" },
      { name: "Regera", slug: "regera" },
      { name: "Jesko", slug: "jesko" },
      { name: "CC850", slug: "cc850" },
    ],
  },
  {
    makeSlug: "lamborghini",
    models: [
      { name: "Murcielago", slug: "murcielago" },
      { name: "Gallardo", slug: "gallardo" },
      { name: "Diablo", slug: "diablo" },
      { name: "147", slug: "147" },
      { name: "Aventador", slug: "aventador" },
      { name: "Huracan", slug: "huracan" },
      { name: "Roadster", slug: "roadster" },
      { name: "Revuelto", slug: "revuelto" },
      { name: "Temerario", slug: "temerario" },
    ],
  },
  {
    makeSlug: "lancia",
    models: [
      { name: "Thema", slug: "thema" },
      { name: "Flavia", slug: "flavia" },
    ],
  },
  {
    makeSlug: "lexus",
    models: [
      { name: "GS", slug: "gs" },
      { name: "LS", slug: "ls" },
      { name: "SC", slug: "sc" },
      { name: "IS", slug: "is" },
      { name: "ES", slug: "es" },
      { name: "CT", slug: "ct" },
      { name: "HS", slug: "hs" },
      { name: "RC", slug: "rc" },
      { name: "LFA", slug: "lfa" },
      { name: "LC", slug: "lc" },
      { name: "UX", slug: "ux" },
    ],
  },
  {
    makeSlug: "lincoln",
    models: [
      { name: "MKZ", slug: "mkz" },
      { name: "Town Car", slug: "town-car" },
      { name: "MKS", slug: "mks" },
      { name: "LS", slug: "ls" },
      { name: "Zephyr", slug: "zephyr" },
      { name: "Continental", slug: "continental" },
      { name: "Mark", slug: "mark" },
    ],
  },
  {
    makeSlug: "lotus",
    models: [
      { name: "Evora", slug: "evora" },
      { name: "Elise", slug: "elise" },
      { name: "Eleven", slug: "eleven" },
      { name: "Esprit", slug: "esprit" },
      { name: "Eagle", slug: "eagle" },
      { name: "Europa", slug: "europa" },
      { name: "Monaco", slug: "monaco" },
      { name: "MEL", slug: "mel" },
      { name: "Elite", slug: "elite" },
      { name: "Eclat", slug: "eclat" },
      { name: "Elan", slug: "elan" },
      { name: "Exige", slug: "exige" },
      { name: "Spa", slug: "spa" },
      { name: "340R", slug: "340r" },
      { name: "Monza", slug: "monza" },
      { name: "2-Eleven", slug: "2-eleven" },
      { name: "Turbo Esprit", slug: "turbo-esprit" },
      { name: "Emira", slug: "emira" },
    ],
  },
  {
    makeSlug: "lucid",
    models: [
      { name: "Air", slug: "air" },
    ],
  },
  {
    makeSlug: "maserati",
    models: [
      { name: "Quattroporte", slug: "quattroporte" },
      { name: "Granturismo", slug: "granturismo" },
      { name: "Coupe", slug: "coupe" },
      { name: "Spyder", slug: "spyder" },
      { name: "Ghibli", slug: "ghibli" },
      { name: "Merak", slug: "merak" },
      { name: "Biturbo", slug: "biturbo" },
      { name: "TC", slug: "tc" },
      { name: "430", slug: "430" },
      { name: "228", slug: "228" },
      { name: "MC20", slug: "mc20" },
      { name: "Grancabrio", slug: "grancabrio" },
      { name: "MCPura", slug: "mcpura" },
    ],
  },
  {
    makeSlug: "maybach",
    models: [
      { name: "62", slug: "62" },
      { name: "57", slug: "57" },
    ],
  },
  {
    makeSlug: "mclaren",
    models: [
      { name: "MP4-12C", slug: "mp4-12c" },
      { name: "P1", slug: "p1" },
      { name: "625C", slug: "625c" },
      { name: "650S", slug: "650s" },
      { name: "675LT", slug: "675lt" },
      { name: "540C", slug: "540c" },
      { name: "570S", slug: "570s" },
      { name: "570GT", slug: "570gt" },
      { name: "600LT", slug: "600lt" },
      { name: "720S", slug: "720s" },
      { name: "SENNA", slug: "senna" },
      { name: "SENNA GTR", slug: "senna-gtr" },
      { name: "GT", slug: "gt" },
      { name: "620R", slug: "620r" },
      { name: "765LT", slug: "765lt" },
      { name: "ELVA", slug: "elva" },
      { name: "Artura", slug: "artura" },
      { name: "750S", slug: "750s" },
      { name: "GTS", slug: "gts" },
    ],
  },
  {
    makeSlug: "mercury",
    models: [
      { name: "Grand Marquis", slug: "grand-marquis" },
      { name: "Milan", slug: "milan" },
      { name: "Sable", slug: "sable" },
      { name: "Montego", slug: "montego" },
      { name: "Cougar", slug: "cougar" },
      { name: "Tracer", slug: "tracer" },
      { name: "Mystique", slug: "mystique" },
      { name: "Capri", slug: "capri" },
      { name: "Topaz", slug: "topaz" },
      { name: "Lynx", slug: "lynx" },
      { name: "MARQUIS", slug: "marquis" },
      { name: "Zephyr", slug: "zephyr" },
      { name: "Marauder", slug: "marauder" },
    ],
  },
  {
    makeSlug: "merkur",
    models: [
      { name: "XR4Ti", slug: "xr4ti" },
      { name: "Scorpio", slug: "scorpio" },
    ],
  },
  {
    makeSlug: "mini",
    models: [
      { name: "Cooper", slug: "cooper" },
      { name: "Clubman", slug: "clubman" },
      { name: "Cooper Convertible", slug: "cooper-convertible" },
      { name: "Hardtop", slug: "hardtop" },
      { name: "Countryman", slug: "countryman" },
      { name: "Cooper Coupe", slug: "cooper-coupe" },
      { name: "Cooper Roadster", slug: "cooper-roadster" },
      { name: "Paceman", slug: "paceman" },
    ],
  },
  {
    makeSlug: "mitsubishi",
    models: [
      { name: "Lancer", slug: "lancer" },
      { name: "Galant", slug: "galant" },
      { name: "Eclipse", slug: "eclipse" },
      { name: "i-MiEV", slug: "i-miev" },
      { name: "Mirage", slug: "mirage" },
      { name: "Expo", slug: "expo" },
      { name: "3000GT", slug: "3000gt" },
      { name: "Diamante", slug: "diamante" },
      { name: "Lancer SportBack", slug: "lancer-sportback" },
      { name: "Lancer Evolution", slug: "lancer-evolution" },
      { name: "Mirage G4", slug: "mirage-g4" },
      { name: "Precis", slug: "precis" },
      { name: "Space Wagon", slug: "space-wagon" },
      { name: "Sigma", slug: "sigma" },
      { name: "Starion", slug: "starion" },
      { name: "Tredia", slug: "tredia" },
      { name: "Cordia", slug: "cordia" },
    ],
  },
  {
    makeSlug: "moke",
    models: [
      { name: "Gen 1 EV", slug: "gen-1-ev" },
    ],
  },
  {
    makeSlug: "morgan",
    models: [
      { name: "Roadster", slug: "roadster" },
      { name: "Aero 8", slug: "aero-8" },
      { name: "Plus 8", slug: "plus-8" },
      { name: "Plus Four", slug: "plus-four" },
      { name: "Aero Supersports", slug: "aero-supersports" },
      { name: "SuperSport", slug: "supersport" },
    ],
  },
  {
    makeSlug: "mosler",
    models: [
      { name: "MT900s", slug: "mt900s" },
      { name: "Raptor", slug: "raptor" },
    ],
  },
  {
    makeSlug: "oldsmobile",
    models: [
      { name: "Alero", slug: "alero" },
      { name: "Aurora", slug: "aurora" },
      { name: "Intrigue", slug: "intrigue" },
      { name: "Regency", slug: "regency" },
      { name: "Eighty Eight (88)", slug: "eighty-eight-88" },
      { name: "LSS", slug: "lss" },
      { name: "Cutlass", slug: "cutlass" },
      { name: "Achieva", slug: "achieva" },
      { name: "Cutlass Supreme", slug: "cutlass-supreme" },
      { name: "Ninety Eight (98)", slug: "ninety-eight-98" },
      { name: "Custom Cruiser", slug: "custom-cruiser" },
      { name: "Toronado", slug: "toronado" },
      { name: "Cutlass Calais", slug: "cutlass-calais" },
      { name: "Firenza", slug: "firenza" },
      { name: "Omega", slug: "omega" },
      { name: "Cutlass Ciera", slug: "cutlass-ciera" },
      { name: "Delta 88", slug: "delta-88" },
      { name: "Cutlass Cruiser", slug: "cutlass-cruiser" },
      { name: "Cutlass Salon", slug: "cutlass-salon" },
    ],
  },
  {
    makeSlug: "pagani",
    models: [
      { name: "Huayra", slug: "huayra" },
      { name: "Utopia", slug: "utopia" },
    ],
  },
  {
    makeSlug: "panoz",
    models: [
      { name: "Panoz Roadster", slug: "panoz-roadster" },
    ],
  },
  {
    makeSlug: "plymouth",
    models: [
      { name: "Neon", slug: "neon" },
      { name: "Breeze", slug: "breeze" },
      { name: "Prowler", slug: "prowler" },
      { name: "Acclaim", slug: "acclaim" },
      { name: "Colt", slug: "colt" },
      { name: "Sundance", slug: "sundance" },
      { name: "Laser", slug: "laser" },
      { name: "HORIZON", slug: "horizon" },
      { name: "TURISMO", slug: "turismo" },
      { name: "Reliant", slug: "reliant" },
      { name: "CARAVELLE", slug: "caravelle" },
      { name: "GRAN FURY", slug: "gran-fury" },
      { name: "Conquest", slug: "conquest" },
      { name: "Sapporo", slug: "sapporo" },
      { name: "Champ", slug: "champ" },
    ],
  },
  {
    makeSlug: "polestar",
    models: [
      { name: "Polestar 1", slug: "polestar-1" },
      { name: "Polestar 2", slug: "polestar-2" },
    ],
  },
  {
    makeSlug: "pontiac",
    models: [
      { name: "Vibe", slug: "vibe" },
      { name: "G5", slug: "g5" },
      { name: "Solstice", slug: "solstice" },
      { name: "Wave", slug: "wave" },
      { name: "Grand Prix", slug: "grand-prix" },
      { name: "G6", slug: "g6" },
      { name: "G8", slug: "g8" },
      { name: "G3", slug: "g3" },
      { name: "Pursuit", slug: "pursuit" },
      { name: "GTO", slug: "gto" },
      { name: "Matiz", slug: "matiz" },
      { name: "Bonneville", slug: "bonneville" },
      { name: "Sunfire", slug: "sunfire" },
      { name: "Grand AM", slug: "grand-am" },
      { name: "Firebird", slug: "firebird" },
      { name: "Sunbird", slug: "sunbird" },
      { name: "Firefly", slug: "firefly" },
      { name: "Lemans", slug: "lemans" },
      { name: "6000", slug: "6000" },
      { name: "Parisienne", slug: "parisienne" },
      { name: "Fiero", slug: "fiero" },
      { name: "T1000", slug: "t1000" },
      { name: "Sunbird 2000", slug: "sunbird-2000" },
      { name: "Phoenix", slug: "phoenix" },
      { name: "Grand Lemans", slug: "grand-lemans" },
      { name: "Catalina", slug: "catalina" },
      { name: "J2000", slug: "j2000" },
      { name: "Safari", slug: "safari" },
      { name: "Tempest", slug: "tempest" },
      { name: "Acadian", slug: "acadian" },
      { name: "Sunburst", slug: "sunburst" },
      { name: "Laurentian", slug: "laurentian" },
    ],
  },
  {
    makeSlug: "porsche",
    models: [
      { name: "911", slug: "911" },
      { name: "Boxster", slug: "boxster" },
      { name: "Cayenne", slug: "cayenne" },
      { name: "Cayman", slug: "cayman" },
      { name: "Panamera", slug: "panamera" },
      { name: "918", slug: "918" },
      { name: "944", slug: "944" },
      { name: "928", slug: "928" },
      { name: "924", slug: "924" },
      { name: "968", slug: "968" },
      { name: "Taycan", slug: "taycan" },
      { name: "718 Boxster", slug: "718-boxster" },
      { name: "718 Spyder", slug: "718-spyder" },
      { name: "718 Cayman", slug: "718-cayman" },
    ],
  },
  {
    makeSlug: "rimac",
    models: [
      { name: "Nevera", slug: "nevera" },
      { name: "Nevera R", slug: "nevera-r" },
    ],
  },
  {
    makeSlug: "rolls-royce",
    models: [
      { name: "Phantom", slug: "phantom" },
      { name: "Ghost", slug: "ghost" },
      { name: "Wraith", slug: "wraith" },
      { name: "Silver Dawn", slug: "silver-dawn" },
      { name: "Silver Spur", slug: "silver-spur" },
      { name: "Silver Spirit", slug: "silver-spirit" },
      { name: "Touring Limousine", slug: "touring-limousine" },
      { name: "Corniche", slug: "corniche" },
      { name: "Park Ward", slug: "park-ward" },
      { name: "Silver Seraph", slug: "silver-seraph" },
      { name: "Dawn", slug: "dawn" },
      { name: "Camargue", slug: "camargue" },
      { name: "Flying Spur", slug: "flying-spur" },
      { name: "Spectre", slug: "spectre" },
    ],
  },
  {
    makeSlug: "ruf",
    models: [
      { name: "SCR / R Spyder / Speedster", slug: "scr-r-spyder-speedster" },
      { name: "CTR1", slug: "ctr1" },
      { name: "CTR Anniversary / CTR2 / Turbo R / BTR / RCT", slug: "ctr-anniversary-ctr2-turbo-r-btr-rct" },
      { name: "CTR3 / RtR / Rt12", slug: "ctr3-rtr-rt12" },
    ],
  },
  {
    makeSlug: "saab",
    models: [
      { name: "9-3", slug: "9-3" },
      { name: "9-5", slug: "9-5" },
      { name: "900", slug: "900" },
      { name: "9000", slug: "9000" },
      { name: "9-2X", slug: "9-2x" },
    ],
  },
  {
    makeSlug: "saleen",
    models: [
      { name: "S7", slug: "s7" },
    ],
  },
  {
    makeSlug: "saturn",
    models: [
      { name: "Astra", slug: "astra" },
      { name: "Sky", slug: "sky" },
      { name: "Aura", slug: "aura" },
      { name: "Ion", slug: "ion" },
      { name: "L300", slug: "l300" },
      { name: "L200", slug: "l200" },
      { name: "SL", slug: "sl" },
      { name: "SL1", slug: "sl1" },
      { name: "SL2", slug: "sl2" },
      { name: "SC1", slug: "sc1" },
      { name: "SC2", slug: "sc2" },
      { name: "LS", slug: "ls" },
      { name: "SW1", slug: "sw1" },
      { name: "SW2", slug: "sw2" },
      { name: "LS1", slug: "ls1" },
      { name: "LS2", slug: "ls2" },
      { name: "LW2", slug: "lw2" },
      { name: "LW1", slug: "lw1" },
      { name: "LW200", slug: "lw200" },
      { name: "LW300", slug: "lw300" },
      { name: "SL3", slug: "sl3" },
    ],
  },
  {
    makeSlug: "shelby",
    models: [
      { name: "Cobra", slug: "cobra" },
      { name: "GT", slug: "gt" },
    ],
  },
  {
    makeSlug: "smart",
    models: [
      { name: "Fortwo", slug: "fortwo" },
      { name: "EQ Fortwo", slug: "eq-fortwo" },
      { name: "Fortwo Electric Drive", slug: "fortwo-electric-drive" },
    ],
  },
  {
    makeSlug: "spyker",
    models: [
      { name: "C8", slug: "c8" },
      { name: "C12", slug: "c12" },
      { name: "D8/D12", slug: "d8-d12" },
    ],
  },
  {
    makeSlug: "ssc-north-america",
    models: [
      { name: "Tuatara", slug: "tuatara" },
      { name: "Striker", slug: "striker" },
      { name: "Aggressor", slug: "aggressor" },
    ],
  },
  {
    makeSlug: "subaru",
    models: [
      { name: "Legacy", slug: "legacy" },
      { name: "Outback", slug: "outback" },
      { name: "Forester", slug: "forester" },
      { name: "Impreza", slug: "impreza" },
      { name: "WRX", slug: "wrx" },
      { name: "BRZ", slug: "brz" },
      { name: "SVX", slug: "svx" },
      { name: "Justy", slug: "justy" },
      { name: "Loyale", slug: "loyale" },
      { name: "Brat", slug: "brat" },
      { name: "XT", slug: "xt" },
      { name: "XT6", slug: "xt6" },
      { name: "DL", slug: "dl" },
      { name: "GL", slug: "gl" },
      { name: "GL-10", slug: "gl-10" },
      { name: "RX", slug: "rx" },
      { name: "Standard", slug: "standard" },
      { name: "GLF", slug: "glf" },
    ],
  },
  {
    makeSlug: "suzuki",
    models: [
      { name: "Aerio", slug: "aerio" },
      { name: "SX4", slug: "sx4" },
      { name: "Kizashi", slug: "kizashi" },
      { name: "Swift", slug: "swift" },
      { name: "Forenza", slug: "forenza" },
      { name: "Reno", slug: "reno" },
      { name: "Esteem", slug: "esteem" },
      { name: "Verona", slug: "verona" },
      { name: "Forsa", slug: "forsa" },
    ],
  },
  {
    makeSlug: "tesla",
    models: [
      { name: "Model S", slug: "model-s" },
      { name: "Roadster", slug: "roadster" },
      { name: "Model X", slug: "model-x" },
      { name: "Model 3", slug: "model-3" },
      { name: "Model Y", slug: "model-y" },
      { name: "Cybercab", slug: "cybercab" },
    ],
  },
  {
    makeSlug: "triumph",
    models: [
      { name: "TR7", slug: "tr7" },
      { name: "TR8", slug: "tr8" },
    ],
  },
  {
    makeSlug: "volvo",
    models: [
      { name: "S60", slug: "s60" },
      { name: "S80", slug: "s80" },
      { name: "V60", slug: "v60" },
      { name: "XC60", slug: "xc60" },
      { name: "XC70", slug: "xc70" },
      { name: "S40", slug: "s40" },
      { name: "V50", slug: "v50" },
      { name: "C70", slug: "c70" },
      { name: "V70", slug: "v70" },
      { name: "XC90", slug: "xc90" },
      { name: "C30", slug: "c30" },
      { name: "940 Series", slug: "940-series" },
      { name: "960 Series", slug: "960-series" },
      { name: "850 Series", slug: "850-series" },
      { name: "V60CC", slug: "v60cc" },
      { name: "S60 Cross Country", slug: "s60-cross-country" },
      { name: "S90", slug: "s90" },
      { name: "V90", slug: "v90" },
      { name: "V90CC", slug: "v90cc" },
      { name: "240 Series", slug: "240-series" },
      { name: "740 Series", slug: "740-series" },
      { name: "780 Series", slug: "780-series" },
      { name: "760 Series", slug: "760-series" },
      { name: "V40", slug: "v40" },
      { name: "S70", slug: "s70" },
      { name: "260 Series", slug: "260-series" },
      { name: "C70 / C30", slug: "c70-c30" },
    ],
  },
  {
    makeSlug: "yugo",
    models: [
      { name: "Yugo 45", slug: "yugo-45" },
      { name: "Yugo 65", slug: "yugo-65" },
      { name: "Yugo 55", slug: "yugo-55" },
      { name: "102, GV", slug: "102-gv" },
    ],
  },
  {
    makeSlug: "zeekr",
    models: [
      { name: "RT", slug: "rt" },
    ],
  },
];

async function main() {
  let created = 0;
  let alreadyExisted = 0;
  let skippedMakes = 0;

  for (const entry of MAKE_MODELS) {
    const make = await prisma.catalogMake.findUnique({
      where: { slug: entry.makeSlug },
      select: { id: true },
    });
    if (!make) {
      console.warn(`⚠ No catalog_makes row for slug "${entry.makeSlug}", skipping`);
      skippedMakes += 1;
      continue;
    }

    for (const model of entry.models) {
      const existing = await prisma.catalogModel.findUnique({
        where: { makeId_slug: { makeId: make.id, slug: model.slug } },
        select: { id: true },
      });
      if (existing) {
        alreadyExisted += 1;
        continue;
      }
      await prisma.catalogModel.create({
        data: {
          id: `nhtsa-${entry.makeSlug}-${model.slug}`,
          makeId: make.id,
          slug: model.slug,
          name: model.name,
        },
      });
      created += 1;
    }
    console.log(`+ ${entry.makeSlug}: ${entry.models.length} models processed`);
  }

  console.log(
    `\nDone. Created ${created} new models, ${alreadyExisted} already existed, ${skippedMakes} makes skipped (no matching catalog_makes row).`,
  );
  const total = await prisma.catalogModel.count();
  console.log(`catalog_models total: ${total}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
